jQuery(document).ready(function(){setTimeout(function(){if(PSBdat.VER_status){PSBeng.showAlert("<h3>Congratulation!!!</h3> <h4>Paladin SEO Manager was updated to ver "+PSBdat.data.version+'</h4><div style="text-align:left;"'+PSBdat.update_text+"</div>",75E3,"auto","550px");$(".custom-icon-off").live("click",function(){$.unblockUI()})}},5E3);$(document).ajaxStart(function(){if(!PSBeng.data.ajaxBlock||PSBeng.data.gen_progress)return;$.unblockUI();$.blockUI({css:{border:"none",padding:"15px",backgroundColor:"#000",
"-webkit-border-radius":"10px","-moz-border-radius":"10px",opacity:.5,color:"#fff"}})});$(document).ajaxStop(function(){if(!PSBeng.data.gen_progress)$.unblockUI()});PSBeng.init()});
var PSBeng={data:{lastDataRequest:{},last_seo_power:0,ajaxBlock:true,last_alert_text:"",gen_progress:false},progress:{show:function(){var progress=$("#progress_bar_container").html();progress+='<div class="gen_status_bar" style="margin-top:-30px; "><span>Start process!</span></br></div>';$.unblockUI();$.blockUI({message:progress,css:{border:"none",padding:"0px",width:"50%",left:"25%",backgroundColor:"transparent","-webkit-border-radius":"10px","-moz-border-radius":"10px",opacity:1,color:"#fff"}});
PSBeng.progress.update(0,"")},update:function(val,text,last_pack_status){var val=val>100?100:val;if(text)PSBeng.progress.refreshText(text,last_pack_status);$(".blockUI #progress_bar .ui-progress").animateProgress(val)},remove:function(){$.unblockUI()},refreshText:function(text,last_pack_status){var $g_s_b=$(".gen_status_bar");var text="<p>"+text+"</p>";var $g_s_b_p=$(".gen_status_bar>p");if($g_s_b_p.length>5)$g_s_b_p.first().remove();if(last_pack_status){$g_s_b_p.last().find("span").remove();var l_p_s=
last_pack_status?last_pack_status:"";$g_s_b_p.last().html($g_s_b_p.last().html()+l_p_s)}$g_s_b.append(text)}},showAlert:function(text,time,cursor,width){$.unblockUI();var time=time?time:4E3;var block_ui={fadeIn:700,fadeOut:700,timeout:time,showOverlay:false,centerY:false,css:{width:width?width:"350px",top:"100px",left:"","font-size":"120%",right:"30px",border:"2px solid #FF0808",padding:"15px",backgroundColor:"#fff","-webkit-border-radius":"5px","-moz-border-radius":"5px",opacity:.85,color:"#FF0808",
cursor:cursor?cursor:"wait","z-index":9999999}};setTimeout(function(){$.blockUI($.extend({message:text},block_ui))},100)},showError:function(data){$.unblockUI();var block_ui={fadeIn:700,fadeOut:700,timeout:4E3,showOverlay:false,centerY:false,css:{width:"350px",top:"100px",left:"","font-size":"120%",right:"30px",border:"2px solid #fff",padding:"15px",backgroundColor:"red","-webkit-border-radius":"5px","-moz-border-radius":"5px",opacity:.7,color:"#fff"}};var text='<p style="text-align:left;font-size:20px;">';
$.each(data,function(k,v){text+='<span style="font-size:18px;">Error:</span> '+v+"</br>"});text+="</p>";setTimeout(function(){$.blockUI($.extend({message:text},block_ui))},200)},showGenerateConfirm:function(text){},getEditSEO:function($container,url){},initTabAjaxContent:function(){$(".nav-tabs.ajax-tabs-content a").on("show",function(e){var $this=$(this);var func=$this.parents(".nav-tabs.ajax-tabs-content").attr("data-function");if($this.data("loaded")!=1){var notshowAjaxBlock=true;$this.parents(".nav-tabs.ajax-tabs-content").find("a").each(function(){if($(this).data("loaded")==
1)notshowAjaxBlock=false});$this.data("loaded",1);if(notshowAjaxBlock)PSBeng.data.ajaxBlock=false;var url=$this.attr("data-href");eval(func+"($($this.attr('href')), url)")}});$(".nav-tabs.ajax-tabs-content a:first").trigger("show")},init:function(){$(".select_all_behavior").on("click",function(){var target_checkbox_class=$(this).attr("data-target");var $checkbox=$("."+target_checkbox_class+"[type=checkbox]");if(!$checkbox.length)$checkbox=$("."+target_checkbox_class+" input[type=checkbox]");$checkbox.attr("checked",
this.checked)});PSBeng.setRadioControllValue();$("*[data-toggle=tooltip]").tooltip({html:true});jscolor.init();$(".shar-bar-position .btn").click(function(){$(".shar-bar-position .btn").removeClass("btn-success");$(this).addClass("btn-success")});PSBeng.modalLoadInit();setTimeout(function(){PSBeng.initTabAjaxContent()},500);$(".accordion-inner .close").click(function(){$(this).parents(".accordion-group").find(".collapse").collapse("hide")});$(".nav-tabs li").click(function(){var menu_id=$(this).parents(".nav-tabs").attr("id");
$.cookie(menu_id,$(this).index())});$(".nav-tabs").each(function(){var menu_id=$(this).attr("id");var index=$.cookie(menu_id);if($.cookie(menu_id))$("#"+menu_id+">*:eq("+index+") a").tab("show")});$(".seo_button_pattern").tooltip();setTimeout(function(){$(".cke_toolbox :last-child .cke_toolgroup a").tooltip({placement:"bottom",html:true})},3E3);$(".grider").grider({countRow:true,countRowAdd:true});var $modal_header=$(".grider").parents(".modal").find(".modal-header");$modal_header.append($(".grider caption"));
$(".on_off").iphoneStyle({width:50,height:70,onChange:function(self){if(!$(self).parents(".controls").find("input.on_off").hasClass("noAlert")){PSBeng.data.ajaxBlock=false;PSBeng.showAlert("Saving...")}PSBeng.action($(self).parents(".controls").find("input[data-action]"))}});$(".all_off").iphoneStyle({width:50,height:70,onChange:function(self){if(!$(self).parents(".controls").find("input.on_off").hasClass("noAlert")){PSBeng.data.ajaxBlock=false;PSBeng.showAlert("Saving...")}PSBeng.action($(self).parents(".controls").find("input[data-action]"))}});
PSBeng.patternLine.init();PSBeng.patternAddValue.init();PSBeng.setPowerStatus.gaugeAnimate();PSBeng.handler()},setCondition:function(){var condition=$("#modal-prepareGenerate").find(".block_gener_mode a.active").attr("data-condition");if(typeof condition==="undefined"||condition===false)return;PSBeng.data.lastDataRequest["additionData[condition]"]=condition;$("#modal-prepareGenerate").find(".block_gener_mode a").removeClass("active");$("#modal-prepareGenerate").find(".block_gener_mode a.gen_only_for_empty").addClass("active")},
setRadioControllValue:function(){$(".radioControllValue a").on("click",function(){$(this).closest(".radioControllValue").find("input[type=hidden]").val($(this).attr("data-condition"))})},patternLine:{init:function(){$("*[data-toggle=popover]").popover({html:true,trigger:"manual"});$(".seo_input_pattern[data-toggle=popover]").click(function(e){if(!$(this).hasClass("active_input"))PSBeng.patternLine.hide();else{e.stopPropagation();return}PSBeng.patternLine.show($(this));$(".popover").click(function(e){e.stopPropagation()});
e.stopPropagation()});$(document).click(function(){PSBeng.patternLine.hide()})},show:function($input){$input.addClass("active_input");$input.popover("show");var $popover=$input.parent().find(".popover");var html=$input.closest(".control-group").find(".pattern_line_label_hide").html();$popover.find(".popover-content").html(html);$popover.find(".close-popup").click(function(){PSBeng.patternLine.hide()});$popover.find("*[data-toggle=tooltip]").tooltip({html:true});PSBeng.patternAddValue.init($popover)},
hide:function(){$(".active_input.seo_input_pattern[data-toggle=popover]").popover("hide");$(".seo_input_pattern[data-toggle=popover]").removeClass("active_input")}},patternAddValue:{data:{active_param:""},init:function($container){if($container&&$container.length){var $button_pattern=$container.find(".seo_button_pattern");var $param_with_addValue=$container.find(".insert-param-with-addValue")}else{var $button_pattern=$(".pattern_line_label .seo_button_pattern");var $param_with_addValue=$(".insert-param-with-addValue")}$button_pattern.click(function(){if(!$(this).attr("data-addValPattern"))$(this).closest("fieldset").find(".active .seo_input_pattern").insertAtCaret($(this).text());
else{$self=$(this);var body_html=PSBeng.patternAddValue.getHtmlForModal($self);$modal=$("#modal-setAdditionPatternValue");$modal.find("H4 span").html('"'+$self.attr("data-paramName")+'"');$modal.find(".modal-body").html(body_html);$modal.modal("show");$(".modal-backdrop").click(function(e){e.stopPropagation()});$("#modal-setAdditionPatternValue").click(function(e){e.stopPropagation()});$modal.find("*[data-toggle=tooltip]").tooltip({html:true});PSBeng.patternAddValue.data.active_param=$self}});$param_with_addValue.click(function(){PSBeng.patternAddValue.writeToTemplate($(this))})},
writeToTemplate:function($button){var $parameter=PSBeng.patternAddValue.data.active_param;var $inputs=$button.closest("#modal-setAdditionPatternValue").find("input");var changed=false;var addValPattern=$parameter.attr("data-addValPattern");var addValue=PSBeng.patternAddValue.getAddValFromParam($parameter);var av_names=addValue.name;var av_values=addValue.value;$inputs.each(function(){var name=$(this).attr("name");var def_val=av_values[$.inArray(name,av_names)];var input_val=$(this).val();addValPattern=
addValPattern.replace(name,input_val);if(input_val!=def_val)changed=true});setTimeout(function(){if(changed){var param_addVavue=" "+$.trim($parameter.text())+addValPattern+" ";$parameter.parents("fieldset").find(".active .seo_input_pattern").insertAtCaret(param_addVavue)}else $parameter.parents("fieldset").find(".active .seo_input_pattern").insertAtCaret($parameter.text())},500)},getAddValFromParam:function($parameter){var addValue=eval("("+$self.attr("data-addValue")+")");return addValue},getHtmlForModal:function($parameter){var form_element=
{"int":'<input name="%s" class="span2" value="%s" min="%s" max="%s" type="number" data-toggle="tooltip" data-original-title="Must be between %s to %s" data-placement="right">',"str":'<input name="%s" class="span2" value="%s" minlength="%s" maxlength="%s" type="text" data-toggle="tooltip" data-temp-min="%s" data-original-title="Can be max %s character" data-placement="right">'};var form_fieldset='<tr><td><fieldset><div class="control-group"><label class="control-label">%s</label><div class="controls">%s</div></div></fieldset></td></tr>';
var form_container_start='<form class="form-horizontal"><table class="table table-condensed no-border"><tbody>';var form_container_end="</tbody></table></form>";var addValue=PSBeng.patternAddValue.getAddValFromParam($parameter);var av_names=addValue.name;var av_values=addValue.value;var paramName=$parameter.attr("data-paramName").toLowerCase();paramName=paramName=="category name"?"categories":paramName;$.each(av_values,function(i,value){if(PSBdat.MD_PatternAddVal[av_names[i]]["text"]=="Text before every ")paramName=
paramName=="example products"?"product":paramName;var text=PSBdat.MD_PatternAddVal[av_names[i]]["text"]+paramName;var type=PSBdat.MD_PatternAddVal[av_names[i]]["type"];var range=PSBdat.MD_PatternAddVal[av_names[i]]["range"];var html_element=sprintf(form_element[type],av_names[i],value,range[0],range[1],range[0],range[1]);var html_fieldset=sprintf(form_fieldset,text,html_element);form_container_start=form_container_start+html_fieldset});var form_container=form_container_start+form_container_end;return form_container}},
handler:function(){$(".btn, .btn-nonstyle").click(function(){PSBeng.action($(this))});$("select[name^=additionData]").change(function(){PSBeng.refreshProdDescrip()});$(".intro-start").click(function(){$(".introjs-overlay").remove();introJs().start()});$(".main_gen_condition").click(function(){var status=Boolean($(this).prop("checked"));$(this).closest("form").find("input[name*=additionData]").not(this).prop("checked",status)})},modalLoadInit:function(){$("[data-toggle=modal]").not(".modal_ajax_activate").click(function(event){event.preventDefault();
$("body,html").animate({scrollTop:0},500);var url=$(this).attr("href");if(url.indexOf("#")!==0)$.get(url,function(data){$('<div class="modal hide fade modal-absolute width_95 ajax_modal">'+data+"</div>").modal().on("hidden",function(){$("[data-toggle=modal]").removeData();$(this).remove();$(".modal-backdrop").remove()});setTimeout(function(){PSBeng.modalLoadInit();$modal_grider=$(".ajax_modal .grider");$modal_grider.grider({countRow:true,countRowAdd:true});$(".ajax_modal .btn").click(function(){PSBeng.action($(this))})},
500)}).success(function(){$("input:text:visible:first").focus()})}).addClass("modal_ajax_activate")},refreshProdDescrip:function(data){if(!data){var data=$("select[name^=additionData]").val();data="data[category]="+data;data+="&metaData[action]=refreshProdDescrip";PSBeng.ajax(data,"json","PSBeng.refreshProdDescrip")}else $.each(data,function(key,val){var editor=CKEDITOR.instances["product_"+key+"_text"];editor.setData(val)})},action:function($btn){var action=$btn.attr("data-action");if(typeof action===
"undefined"||action===false)return;$(".ckeditor textarea").each(function(){var $textarea=$(this);$textarea.val(CKEDITOR.instances[$textarea.attr("id")].getData())});var afterAction=$btn.attr("data-afterAction")?$btn.attr("data-afterAction"):action;if($btn.attr("data-jsaction")){eval($btn.attr("data-jsaction"));return}if($btn.attr("data-jsbeforeaction"))eval($btn.attr("data-jsbeforeaction"));var data_entity=$btn.attr("data-entity")?$btn.attr("data-entity"):"";var formData=getFormData();if(formData){if(data_entity)$.extend(formData,
{"metaData[entity]":data_entity});PSBeng.data.lastDataRequest=formData}formData=PSBeng.data.lastDataRequest;$.extend(formData,{"metaData[action]":action});PSBeng.ajax(formData,"json","PSBeng."+afterAction);function getFormData(){var formData=false;if($btn.attr("data-data")&&$btn.attr("data-data")!="")formData={"data":$btn.attr("data-data")};else if($btn.attr("data-scope")&&$btn.attr("data-scope")!=""){var $scope="";formData={};eval("$scope = $btn"+$btn.attr("data-scope")+";");var scope_data=$scope.serializeArray();
for(index=0;index<scope_data.length;++index){var data=scope_data[index];eval('$.extend(formData, {"'+data.name+'" : data.value});')}}return formData}},testGenerate:function(data){$("#modal-testGenerate").find("p.seo_text").html('<table class="result_test_generet table">'+data.seo_text+"</table>");$("#modal-testGenerate").modal("show")},prepareGenerate:function(data){PSBeng.data.curr_pack=0;var $block_gener_mode=$("#modal-prepareGenerate").find(".block_gener_mode");$block_gener_mode.attr("class","");
$block_gener_mode.addClass("generate-for-"+data.entity_category).addClass("block_gener_mode");$("#modal-prepareGenerate").find("p.total_text").html(data.total_text);$("#modal-prepareGenerate").find("p.confirm_text").html(data.confirm_text);$("#modal-prepareGenerate").modal("show");PSBeng.data.total_pack=(100/(data.total_genPack+2)).toFixed(2)},processGenerate:function(data,pack_status){if(!PSBeng.data.gen_progress){PSBeng.data.gen_progress=true;PSBeng.progress.show()}var curr_pack=PSBeng.data.curr_pack;
var progress=(new Number(PSBeng.data.total_pack*(curr_pack+1))).toFixed(2);var status={"success":'<span class="label label-success"> ...done!</span>',"error":'<span class="label label-warning"> ...Error</span>'};var preloader='<span class="preload"><img src="'+PSBdat.HTTP_SERVER+'view/stylesheet/superseobox/images/gen_process__.gif"></img></span>';var text_line="generated pack "+curr_pack+" "+preloader;if(pack_status){var pack_status=status[pack_status];if(pack_status=="error")text_line="re-"+text_line}PSBeng.progress.update(progress,
text_line,pack_status);if(data.process=="go"){formData=PSBeng.data.lastDataRequest;$.extend(formData,{"metaData[action]":"processGenerate","metaData[pack]":curr_pack});PSBeng.data.curr_pack++;ajaxGenPack(formData)}else if(data.process=="stop"){formData=PSBeng.data.lastDataRequest;$.extend(formData,{"metaData[action]":"endGenerate"});PSBeng.ajax(formData,"json","PSBeng.endGenerate")}function ajaxGenPack(data){var url=PSBdat.url.ajax;$.ajax({url:url,dataType:"json",type:"POST",data:data,success:function(data){pack_status=
"success";PSBeng.processGenerate(data,pack_status)},statusCode:{404:function(){pack_status="error";PSBeng.data.curr_pack--;PSBeng.processGenerate({process:"go"},pack_status)},502:function(){pack_status="error";PSBeng.data.curr_pack--;PSBeng.processGenerate({process:"go"},pack_status)}}})}},endGenerate:function(data){setTimeout(function(){PSBeng.progress.update(100,"All done!",'<span class="label label-success"> ...done!</span>')},1E3);PSBeng.data.gen_progress=false;PSBeng.setPowerStatus.refreshAll(data)},
changeAutoGenerate:function(data){},prepareClearGenerate:function(data){$("#modal-prepareClearGenerate").find("p.total_text").html(data.total_text);$("#modal-prepareClearGenerate").find("p.confirm_text").html(data.confirm_text);$("#modal-prepareClearGenerate").modal("show")},startClearGenerate:function(data){PSBeng.setPowerStatus.refreshAll(data)},showModalTown:function(data){var $parameterWT=$("#modal-parameterWT");var $body=$parameterWT.find(".modal-body");$parameterWT.find(".modal-header caption").remove();
$body.html('<table class="table table-hover grider-wtwc"><thead><tr class="top_table"></tr></thead><tbody></tbody></table>');var html_header="";var html_body="";$.each(data.languages,function(i,l_key){html_header+="<th>Town name in "+l_key+"</th>"});$.each(data.towns,function(i,tow){html_body+="<tr>";$.each(tow,function(ii,tw){html_body+='<td> <input type="text" data-gride-pattern="data[patternsSettings][wt][data]['+data.languages[ii]+'][%i1]" name="data[patternsSettings][wt][data]['+data.languages[ii]+
"]["+i+']"  value="'+tw+'"></td>'});html_body+="</tr>"});$parameterWT.find("thead .top_table").html(html_header);$parameterWT.find("tbody").html(html_body);$parameterWT.find(".modal-footer input#patternsSettings_wt_country").val(data.country);$parameterWT.find(".modal-footer input#patternsSettings_wt_featureCode").val(data.featureCode);$("#modal-parameterWT").modal("show");$grider=$parameterWT.find(".grider-wtwc");$grider.grider({countRow:true,countRowAdd:true});var $modal_header=$grider.parents(".modal").find(".modal-header");
$modal_header.append($(".grider-wt caption"))},showModalCountry:function(data){var $parameterWC=$("#modal-parameterWC");var $body=$parameterWC.find(".modal-body");$parameterWC.find(".modal-header caption").remove();$body.html('<table class="table table-hover grider-wtwc"><thead><tr class="top_table"></tr></thead><tbody></tbody></table>');var html_header="";var html_body="";$.each(data.languages,function(i,l_key){html_header+="<th>Country name in "+l_key+"</th>"});$.each(data.continents,function(i,
con){html_body+="<tr>";$.each(con,function(ii,co){html_body+='<td> <input type="text" data-gride-pattern="data[patternsSettings][wc][data]['+data.languages[ii]+'][%i1]" name="data[patternsSettings][wc][data]['+data.languages[ii]+"]["+i+']"  value="'+co+'"></td>'});html_body+="</tr>"});$parameterWC.find("thead .top_table").html(html_header);$parameterWC.find("tbody").html(html_body);$parameterWC.find(".modal-footer input#patternsSettings_wc_continent").val(data.continent);$("#modal-parameterWC").modal("show");
$grider=$parameterWC.find(".grider-wtwc");$grider.grider({countRow:true,countRowAdd:true});var $modal_header=$grider.parents(".modal").find(".modal-header");$modal_header.append($(".grider-wt caption"))},repeatAction:function(data){PSBeng.afterAction(data)},afterAction:function(data){if(!data)return;if(data.error)PSBeng.showError(data.error);if(data.alert&&!data.power)PSBeng.showAlert(JSON.stringify(data.alert));if(data.status=="reload")setTimeout(function(){location.reload()},3E3);if(data.status==
"ajax-reload")setTimeout(function(){var metaData_action="&metaData[action]=getAjaxPage";PSBeng.ajax(metaData_action,"text")},3E3);if(data.power){data.status="refresh";data.alert_text=data.alert;PSBeng.setPowerStatus.refreshAll(data)}},afterSnipetToolsCahnge:function(data){data.status="refresh";data.alert_text=data.alert;PSBeng.setPowerStatus.refreshAll(data)},afterSupport:function(data){if(data.error)PSBeng.showError(data.error);if(data.alert){$("#support-idea textarea,#support textarea").val("");
PSBeng.showAlert(JSON.stringify(data.alert),5E3)}},afterImport:function(data){setTimeout(function(){location.reload()},1E3);PSBeng.showAlert(JSON.stringify(data.alert))},afterExport:function(data){$(".export_area").val(data.data).select();PSBeng.showAlert(JSON.stringify(data.alert))},refreshReviewTable:function(data){$(".modal .close").click();setTimeout(function(){$("."+data.data+"_open").click()},200)},ajax:function(data,dataType,func,url,timeOutForAlert){if(!url||url=="")var url=PSBdat.url.ajax;
if(!dataType||dataType=="")var dataType="text";$.ajax({url:url,dataType:dataType,type:"POST",data:data,success:function(data){if(func&&func!="")eval(func+"(data)");else if(dataType=="text")PSBeng.setHTML(data,timeOutForAlert);else PSBeng.afterAction(data)},statusCode:{404:function(){alert("Error 404")},502:function(){alert("Error 502")}}})},setPowerStatus:{refreshAll:function(data){if(data.status=="refresh")setTimeout(function(){PSBeng.setPowerStatus.setSeoPower(data.power)},800);if(data.alert_text)setTimeout(function(){PSBeng.showAlert(data.alert_text)},
1500);if(data.entityData)setTimeout(function(){PSBeng.setPowerStatus.setStatus(data)},2E3)},setSeoPower:function(new_power){PSBdat.seo_power=new_power;PSBeng.setPowerStatus.gaugeAnimate(true)},gaugeAnimate:function(refresh){var input='<input id="seo-gauge" data-linecap="round" class="knob" data-thickness=".2" data-fgColor="#FE9D00" data-bgColor="#EDEBEC" data-angleOffset=-125 data-angleArc=250 readOnly="true" class="knob" data-width="154" value="70%"><span>SEO POWER</span>';var $seo_gauge_container=
$(".seo-power-box");if(refresh)$seo_gauge_container.html("").html(input);var $seo_gauge_html=$seo_gauge_container.html();$("#seo-gauge").knob();var last_seo_power=PSBeng.data.last_seo_power;PSBeng.data.last_seo_power=PSBdat.seo_power;var new_seo_power=PSBdat.seo_power;timedCount=function(){$seo_gauge_container.html($seo_gauge_html);$("#seo-gauge").val(last_seo_power+"%").knob();if(last_seo_power<new_seo_power){if(last_seo_power<new_seo_power){setTimeout("timedCount();",50);last_seo_power++}}else if(last_seo_power>
new_seo_power){setTimeout("timedCount();",50);last_seo_power--}};timedCount()},setStatus:function(data){var category=data.entityData.category.name;var entity=data.entityData.entity.name;var internal_entity=data.entityData.internal_entity.name;var category_status=data.genStatus;if(entity=="all"||entity=="CPBI_urls"&&internal_entity==""){var $statusEntities=$("#seo_generator_"+category).find(".status");setStatus($statusEntities,data.genStatus)}else if(category!="reviews"&&category!="related_prod"){if(entity==
"CPBI_urls"&&internal_entity!="")var $statusEntity=$("div[id^=TDKT_"+category+"-"+entity+"-"+internal_entity+"]").find(".status");else if(category=="descrip")var $statusEntity=$("a[href=#seo_"+category+"_"+entity+"]").find(".status");else var $statusEntity=$("div[id^=TDKT_"+category+"-"+entity+"]").find(".status");setStatus($statusEntity,data.genStatus);var $statusEntities=$("#seo_generator_"+category).find(".status");category_status=false;$statusEntities.each(function(){if($(this).hasClass("status-on"))category_status=
true})}var $statusCategory=$("a[href=#seo_generator_"+category+"]").find(".status");setStatus($statusCategory,category_status);function setStatus($el_status,status){$el_status.removeClass("status-off").removeClass("status-on");if(status)$el_status.addClass("status-on");else $el_status.addClass("status-off")}}},setHTML:function(html,timeOut){$(".content").html(html);PSBeng.init();introStart(document,introfunction);if(PSBeng.data.last_alert_text){var timeOut=timeOut?timeOut:800;setTimeout(function(){PSBeng.showAlert(PSBeng.data.last_alert_text);
PSBeng.data.last_alert_text=""},timeOut)}},save:function(data){}};function sprintf(format){for(var i=1;i<arguments.length;i++)format=format.replace(/%s/,arguments[i]);return format}
jQuery.fn.extend({insertAtCaret:function(myValue){return this.each(function(i){if(document.selection){this.focus();var sel=document.selection.createRange();sel.text=myValue;this.focus()}else if(this.selectionStart||this.selectionStart=="0"){var startPos=this.selectionStart;var endPos=this.selectionEnd;var scrollTop=this.scrollTop;this.value=this.value.substring(0,startPos)+myValue+this.value.substring(endPos,this.value.length);this.focus();this.selectionStart=startPos+myValue.length;this.selectionEnd=
startPos+myValue.length;this.scrollTop=scrollTop}else{this.value+=myValue;this.focus()}})}});
(function($){$.fn.animateProgress=function(progress,callback){return this.each(function(){$(this).animate({width:progress+"%"},{duration:200,easing:"swing",step:function(progress){var labelEl=$(".ui-label",this),valueEl=$(".value",labelEl);if(Math.ceil(progress)<20&&$(".ui-label",this).is(":visible"))labelEl.hide();else if(labelEl.is(":hidden"))labelEl.fadeIn();if(Math.ceil(progress)==100){labelEl.text("Done");setTimeout(function(){labelEl.fadeOut()},1E3)}else valueEl.text(Math.ceil(progress)+"%")},
complete:function(scope,i,elem){if(callback)callback.call(this,i,elem)}})})}})(jQuery);